# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 605)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(600, 605))
        MainWindow.setMaximumSize(QtCore.QSize(600, 605))
        MainWindow.setStyleSheet("QWidget {\n"
"color: black;\n"
"font-family: Montserrat;\n"
"font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"background-color: #d9d9d9;\n"
"}\n"
"\n"
"QComboBox:hover:!pressed\n"
"{\n"
"  border: 1px solid #d9d9d9;\n"
"}\n"
"\n"
"QComboBox {\n"
"border: none;\n"
"border-radius: 4px;\n"
"padding-left: 10px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"image: url(:/buttons/icons/arrow_drop_down_FILL0_wght400_GRAD0_opsz48.svg);\n"
"width: 18px;\n"
"height: 18px;\n"
"margin-right: 10px;\n"
"}\n"
"\n"
"QComboBox:on {\n"
"\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"font-size: 12px;\n"
"border: 1px solid rgba(0, 0, 0, 10%);\n"
"padding: 5px;\n"
"background-color: #fff;\n"
"outline: 0px;\n"
"}\n"
"\n"
"QComboBox QListView::item {\n"
"padding-left: 10px;\n"
"background-color: #fff;\n"
"}\n"
"\n"
"QComboBox QListView::item:hover {\n"
"background-color: #d9d9d9;\n"
"}\n"
"\n"
"QComboBox QListView::item:selected {\n"
"background-color: #d9d9d9;\n"
"}")
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 601, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.title = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.title.setContentsMargins(0, 0, 0, 0)
        self.title.setSpacing(0)
        self.title.setObjectName("title")
        self.searchMe = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchMe.sizePolicy().hasHeightForWidth())
        self.searchMe.setSizePolicy(sizePolicy)
        self.searchMe.setMinimumSize(QtCore.QSize(80, 0))
        self.searchMe.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/buttons/icons/near_me_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchMe.setIcon(icon)
        self.searchMe.setObjectName("searchMe")
        self.title.addWidget(self.searchMe)
        self.frame = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.title.addWidget(self.frame)
        self.hide_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_button.sizePolicy().hasHeightForWidth())
        self.hide_button.setSizePolicy(sizePolicy)
        self.hide_button.setMinimumSize(QtCore.QSize(80, 0))
        self.hide_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/icons/remove_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hide_button.setIcon(icon1)
        self.hide_button.setObjectName("hide_button")
        self.title.addWidget(self.hide_button)
        self.close_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMinimumSize(QtCore.QSize(80, 0))
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/icons/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setObjectName("close_button")
        self.title.addWidget(self.close_button)
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 50, 601, 321))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.info = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.info.setContentsMargins(0, 0, 0, 0)
        self.info.setObjectName("info")
        self.Text = QtWidgets.QTextBrowser(self.gridLayoutWidget)
        self.Text.setEnabled(True)
        self.Text.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.Text.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.Text.setObjectName("Text")
        self.info.addWidget(self.Text, 0, 1, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 540, 581, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.searchtext = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.searchtext.setObjectName("searchtext")
        self.horizontalLayout.addWidget(self.searchtext)
        self.searchbutton = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchbutton.sizePolicy().hasHeightForWidth())
        self.searchbutton.setSizePolicy(sizePolicy)
        self.searchbutton.setMinimumSize(QtCore.QSize(75, 0))
        self.searchbutton.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/buttons/icons/travel_explore_FILL0_wght400_GRAD0_opsz48.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.searchbutton.setIcon(icon3)
        self.searchbutton.setObjectName("searchbutton")
        self.horizontalLayout.addWidget(self.searchbutton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
