# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.WindowModality.NonModal)
        MainWindow.resize(600, 605)
        MainWindow.setMaximumSize(QtCore.QSize(600, 605))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/close/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("QWidget {\n"
"    color: black;\n"
"    font-family: Montserrat;\n"
"    font-size: 16pt;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #1e90ff;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: 1 px solid #ced4da;\n"
"    border-radius: 4px;\n"
"    padding-left: 10 px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    border: 0px;\n"
"}\n"
"\n"
"QComboBox::down-arrow {\n"
"    image: url(:/buttons/hide.svg);\n"
"    width:18px;\n"
"    height: 18px;\n"
"    margin-right: 10px;\n"
"}\n"
"\n"
"QComboBox: on {\n"
"    border: 4px solid #c2dbfe\n"
"}\n"
"\n"
"QComboBox QListView {\n"
"    font-size: 12px;\n"
"    border: 1px solid rgba(0,0,0,10%);\n"
"    padding: 5px;\n"
"    background-color: #fff;\n"
"    outline: 0px;\n"
"}\n"
"\n"
"QComboBox QListView::item {\n"
"    padding-left: 10px;\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"QComboBox QListView::item:hover {\n"
"    background-color: #1e90ff;\n"
"}\n"
"\n"
"QComboBox QListView::item:selected {\n"
"    background-color: #1e90ff;\n"
"}")
        MainWindow.setAnimated(True)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(430, 0, 171, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.hide_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hide_button.sizePolicy().hasHeightForWidth())
        self.hide_button.setSizePolicy(sizePolicy)
        self.hide_button.setMaximumSize(QtCore.QSize(11111, 1111))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.hide_button.setFont(font)
        self.hide_button.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.DefaultContextMenu)
        self.hide_button.setAutoFillBackground(False)
        self.hide_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttons/hide.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.hide_button.setIcon(icon1)
        self.hide_button.setAutoDefault(False)
        self.hide_button.setDefault(False)
        self.hide_button.setFlat(False)
        self.hide_button.setObjectName("hide_button")
        self.horizontalLayout.addWidget(self.hide_button)
        self.close_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.close_button.sizePolicy().hasHeightForWidth())
        self.close_button.setSizePolicy(sizePolicy)
        self.close_button.setMaximumSize(QtCore.QSize(11111, 11111))
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setPointSize(16)
        self.close_button.setFont(font)
        self.close_button.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.close_button.setFocusPolicy(QtCore.Qt.FocusPolicy.WheelFocus)
        self.close_button.setStyleSheet("<style>\n"
".material-symbols-outlined {\n"
"  font-variation-settings:\n"
"  \'FILL\' 0,\n"
"  \'wght\' 400,\n"
"  \'GRAD\' 0,\n"
"  \'opsz\' 48\n"
"}\n"
"</style>")
        self.close_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/buttons/close.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.close_button.setIcon(icon2)
        self.close_button.setFlat(False)
        self.close_button.setObjectName("close_button")
        self.horizontalLayout.addWidget(self.close_button)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(0, 560, 601, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(3, 0, 3, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cities = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        self.cities.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cities.sizePolicy().hasHeightForWidth())
        self.cities.setSizePolicy(sizePolicy)
        self.cities.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.cities.setEditable(False)
        self.cities.setCurrentText("")
        self.cities.setFrame(True)
        self.cities.setObjectName("cities")
        self.horizontalLayout_2.addWidget(self.cities)
        self.countries = QtWidgets.QComboBox(self.horizontalLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.countries.sizePolicy().hasHeightForWidth())
        self.countries.setSizePolicy(sizePolicy)
        self.countries.setFocusPolicy(QtCore.Qt.FocusPolicy.NoFocus)
        self.countries.setStyleSheet("\n"
".material-symbols-outlined {  font-variation-settings:\n"
"  \'FILL\' 0,\n"
"  \'wght\' 400,\n"
"  \'GRAD\' 0,\n"
"  \'opsz\' 48\n"
"}")
        self.countries.setEditable(False)
        self.countries.setCurrentText("")
        self.countries.setFrame(True)
        self.countries.setObjectName("countries")
        self.horizontalLayout_2.addWidget(self.countries)
        self.Text = QtWidgets.QLabel(self.centralwidget)
        self.Text.setGeometry(QtCore.QRect(10, 200, 581, 301))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Maximum, QtWidgets.QSizePolicy.Policy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Text.sizePolicy().hasHeightForWidth())
        self.Text.setSizePolicy(sizePolicy)
        self.Text.setObjectName("Text")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Weather"))
        self.Text.setText(_translate("MainWindow", "TextLabel"))
